### PR TITLE
add mapping for AWS neptune metrics with dimension of cluster and role.

### PR DESCRIPTION
**Pull request by jfz**
AWS Neptune metrics by "cluster and role" are published as separate time series, need to add them in addition to existing ones that are by instance or cluster only.

### CODE REVIEW

**Comment by jfz** [comment]
Metrics are published either with dimension of either "DBClusterIdentifier + Role" or "DBInstanceIdentifier".

**Review by brharrington — COMMENTED** [review]
It is unfortunate they have disjoint dimensions for the same metrics. The downside to mapping in both is that if the user just queries based on the name, then they would get duplication since it will match both sets.

Are both really needed? Maybe it would be better to just map in the cluster/role set to minimize the risk of confusion.

**Comment by jfz** [comment]
> It is unfortunate they have disjoint dimensions for the same metrics. The downside to mapping in both is that if the user just queries based on the name, then they would get duplication since it will match both sets.
> 
> Are both really needed? Maybe it would be better to just map in the cluster/role set to minimize the risk of confusion.

Users like to use both, I think it wouldn't be too confusing since the dimension sets do not overlap.

**Comment by brharrington** [comment]
> I think it wouldn't be too confusing since the dimension sets do not overlap.

The issue is more that you have to select both name and one of those other dimensions to get a meaningful aggregate. Typically we recommend structuring data so that it can be meaningfully aggregated if just the name is selected and the dimensions can be used to drill down into the data.

**Pull request merged**
